// <auto-generated />
namespace SMLApplication.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SMLApplicationData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SMLApplicationData));
        
        string IMigrationMetadata.Id
        {
            get { return "201508020439458_SMLApplication.Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
