// <auto-generated />
namespace SMLApplication.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DoctorFeedBack : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DoctorFeedBack));
        
        string IMigrationMetadata.Id
        {
            get { return "201508230143029_DoctorFeedBack"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
